#define TAPPING_TERM 170
#define FLOW_TAP_TERM 85
#define QUICK_TAP_TERM 0
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define COMBO_TERM 50
#define EXTRA_SHORT_COMBOS

#define CAPS_WORD_IDLE_TIMEOUT 0
#define CAPS_WORD_INVERT_ON_SHIFT

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 7
#define MOUSEKEY_MAX_SPEED 16
#define MOUSEKEY_TIME_TO_MAX 48
#define MOUSEKEY_FRICTION 15
#define MOUSEKEY_MOVE_DELTA 1

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 48
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX_SPEED 3
#define MOUSEKEY_WHEEL_TIME_TO_MAX 144
