#define DIODE_DIRECTION COL2ROW
#define MATRIX_ROW_PINS { D4, C6, D7, E6 }
#define MATRIX_COL_PINS { F4, F5, F6, F7, B1, B3 }

#define MASTER_LEFT
#define SOFT_SERIAL_PIN D2

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 1
#define BOOTMAGIC_ROW_RIGHT 4
#define BOOTMAGIC_COLUMN_RIGHT 1

#define CAPS_WORD_IDLE_TIMEOUT 0
#define CAPS_WORD_INVERT_ON_SHIFT

#define TAPPING_TERM 175
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD
#define ACHORDION_STREAK

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 7
#define MOUSEKEY_MAX_SPEED 16
#define MOUSEKEY_TIME_TO_MAX 48
#define MOUSEKEY_FRICTION 15
#define MOUSEKEY_MOVE_DELTA 1

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 48
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX_SPEED 3
#define MOUSEKEY_WHEEL_TIME_TO_MAX 144
